import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import JobCard from '../components/JobCard'


export default function Home() {
  return (
    <div className="bg-slate-100 h-screen">
      <Head>
        <title>Craft Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="flex justify-center max-w-md md:max-w-4xl mx-auto">
        <JobCard />
      </div>
    </div>
  )
}
